src/companent/ClearModal.jsx
src/companent/ClearModal.module.css
src/companent/ExplainBox.jsx
src/companent/ExplainBox.module.css
src/companent/MapShowAll.jsx

마커클릭 시 마커의 정보를 받아와 띄울 오버레이를 생성한다. 
#35

feature : 마커클릭 시 띄울 오버레이를 생성한다.

---

src/companent/ExplainBox.jsx
src/companent/ExplainBox.module.css
src/companent/MapShowAll.jsx

EplainBox의 디자인 개선과 Fade In 을 추가한다.
#37

refactor : ExplainBox의 디자인을 개선한다.

---

src/IntroPage.jsx
src/companent/NavigateBar.jsx
src/index.jsx

- 인트로 페이지를 추가
- 인트로 페이지 내용은 수정요망
- closed issue #40

feature: 인트로 페이지를 추가한다. 

---

src/companent/Map.jsx
src/companent/Map.module.css
src/companent/NavigateBar.jsx
src/companent/UploadBox.jsx

백엔드와 연결하는 코드를 추가한다.
close issue #33

feature : 업로드 기능을 추가한다.

---

src/companent/Map2.jsx
src/index.jsx

백엔드와 연결하는 코드를 추가한다.
close issue #48

feature : 파일을 받는기능 기능을 추가한다.

---

src/companent/Map.module.css
src/companent/UploadBox.jsx
src/companent/UploadBox.module.css

refactor : UploadBox의 디자인을 개선한다.

---

src/companent/IntroPage.jsx
src/companent/IntroPage.module.css

refactor : introPage Text 를 수정한다.

---

src/companent/UploadBox.module.css

refactor : UploadBox의 Design을 수정한다.

---

src/companent/UploadBox.jsx

refactor : 업로드 버그 수정한다.

---

src/companent/Map.jsx
src/companent/Map.module.css

현재 위치로 이동하는 버튼 추가한다.
close issue #55

feature : 현재 위치로 이동하는 버튼 추가한다.

---

src/companent/ExplainBox.jsx
src/companent/Map2.jsx
src/companent/MapShowAll.jsx
src/db/data.json

- 현재 위치로 와지는 버튼 버그 수정
- 서버로 부터 파일을 받아와 마커를 띄우는 코드 수정
- 설명 박스도 서버로부터 데이터를 받아와 띄우는 코드로 수정->더미데이터로 더이상 파일이 안뜸
- close issue #57

refactor : 서버로부터 파일을 가져와 마커를 띄우는 기능을 추가한다.

---

src/companent/IntroPage.module.css

refactor : 배경을 변경한다

---

src/companent/Map3Hour.jsx

feature : CatTower 기능을 개발한다.

---

src/companent/ExplainBox.jsx
src/companent/Map2.jsx
src/companent/Map3Hour.jsx
src/db/data2.json

- 백엔드와 연결이 잘되도록 코드를 수정한다.
- closed issue #62

bug : 백엔드와 연결이 잘되도록 코드를 수정한다.

---

src/companent/ExplainBox.jsx
src/companent/ExplainBox.module.css

refactor : emoji를 추가한다.

---

src/companent/InfoBox.jsx
src/companent/InfoBox.module.css
src/companent/Map.module.css
src/companent/Map2.jsx
src/companent/Map3Hour.jsx

마커를 눌러도 설명버튼이 계속 뜨는거 개선필요
closed issue #67

feature : 설명버튼을 추가한다.

---

src/companent/InfoBox.module.css
src/companent/IntroPage.module.css
src/companent/Map.module.css
src/companent/Map3Hour.jsx
src/companent/UploadBox.jsx

bug : 캣타워와 백엔드를 연결하는 코드를 수정한다.

---

package-lock.json
package.json
src/companent/ExplainBox.jsx
src/companent/InfoBox.jsx
src/companent/InfoBox.module.css
src/companent/IntroPage.module.css
src/companent/Map.module.css
src/companent/Map2.jsx
src/companent/Map3Hour.jsx
src/companent/UploadBox.jsx

refactor: 코드를 수정한다.

---

package-lock.json
package.json
src/companent/InfoBox.jsx
src/companent/Map.module.css
src/companent/Map2.jsx
src/companent/Map3Hour.jsx
src/companent/NavigateBar.jsx
src/companent/UploadBox.jsx

refactor : 위치 마커 추가

---

src/companent/InfoBox.jsx
src/companent/IntroPage.jsx
src/companent/UploadBox.jsx

refactor : 업로드 시간도 함께 전송하는 코드를 추가한다.
